namespace PawsTrack.Presentation.Helpers
{
    internal static class BreedList
    {
        public static readonly string[] All =
        [
            "Mixed Breed",
            "Other",
            "Affenpinscher",
            "Afghan Hound",
            "Airedale Terrier",
            "Akita",
            "Alaskan Malamute",
            "American Bulldog",
            "American English Coonhound",
            "American Eskimo Dog",
            "American Foxhound",
            "American Hairless Terrier",
            "American Leopard Hound",
            "American Staffordshire Terrier",
            "American Water Spaniel",
            "Anatolian Shepherd Dog",
            "Appenzeller Sennenhund",
            "Australian Cattle Dog",
            "Australian Shepherd",
            "Australian Terrier",
            "Azawakh",
            "Barbet",
            "Basenji",
            "Basset Fauve de Bretagne",
            "Basset Hound",
            "Bavarian Mountain Scent Hound",
            "Beagle",
            "Bearded Collie",
            "Bedlington Terrier",
            "Belgian Laekenois",
            "Belgian Malinois",
            "Belgian Sheepdog",
            "Belgian Tervuren",
            "Bergamasco Sheepdog",
            "Berger Picard",
            "Bernese Mountain Dog",
            "Bichon Frise",
            "Biewer Terrier",
            "Black and Tan Coonhound",
            "Black Russian Terrier",
            "Bloodhound",
            "Bluetick Coonhound",
            "Boerboel",
            "Bohemian Shepherd",
            "Border Collie",
            "Border Terrier",
            "Borzoi",
            "Boston Terrier",
            "Bouvier des Flandres",
            "Boxer",
            "Boykin Spaniel",
            "Briard",
            "Brittany",
            "Brussels Griffon",
            "Bull Terrier",
            "Bulldog",
            "Bullmastiff",
            "Cairn Terrier",
            "Canaan Dog",
            "Cane Corso",
            "Cardigan Welsh Corgi",
            "Cavalier King Charles Spaniel",
            "Cesky Terrier",
            "Chesapeake Bay Retriever",
            "Chihuahua",
            "Chinese Crested",
            "Chinese Shar-Pei",
            "Chinook",
            "Chow Chow",
            "Cirneco dell'Etna",
            "Clumber Spaniel",
            "Cocker Spaniel",
            "Collie",
            "Coton de Tulear",
            "Croatian Sheepdog",
            "Curly-Coated Retriever",
            "Dachshund",
            "Dalmatian",
            "Dandie Dinmont Terrier",
            "Danish-Swedish Farmdog",
            "Doberman Pinscher",
            "Dogo Argentino",
            "Dogue de Bordeaux",
            "Dutch Shepherd",
            "English Cocker Spaniel",
            "English Foxhound",
            "English Setter",
            "English Springer Spaniel",
            "English Toy Spaniel",
            "Entlebucher Mountain Dog",
            "Estrela Mountain Dog",
            "Eurasier",
            "Field Spaniel",
            "Finnish Lapphund",
            "Finnish Spitz",
            "Flat-Coated Retriever",
            "French Bulldog",
            "German Pinscher",
            "German Shepherd Dog",
            "German Shorthaired Pointer",
            "German Spitz",
            "German Wirehaired Pointer",
            "Giant Schnauzer",
            "Glen of Imaal Terrier",
            "Golden Retriever",
            "Gordon Setter",
            "Grand Basset Griffon Vendeen",
            "Great Dane",
            "Great Pyrenees",
            "Greater Swiss Mountain Dog",
            "Greyhound",
            "Hamiltonstovare",
            "Harrier",
            "Havanese",
            "Hokkaido",
            "Hovawart",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Irish Red and White Setter",
            "Irish Setter",
            "Irish Terrier",
            "Irish Water Spaniel",
            "Irish Wolfhound",
            "Italian Greyhound",
            "Japanese Chin",
            "Keeshond",
            "Kerry Blue Terrier",
            "Komondor",
            "Kromfohrlander",
            "Kuvasz",
            "Labrador Retriever",
            "Lagotto Romagnolo",
            "Lancashire Heeler",
            "Leonberger",
            "Lhasa Apso",
            "Lowchen",
            "Maltese",
            "Manchester Terrier",
            "Mastiff",
            "Miniature American Shepherd",
            "Miniature Bull Terrier",
            "Miniature Pinscher",
            "Miniature Schnauzer",
            "Mudi",
            "Neapolitan Mastiff",
            "Nederlandse Kooikerhondje",
            "Newfoundland",
            "Norfolk Terrier",
            "Norrbottenspets",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Lundehund",
            "Norwich Terrier",
            "Nova Scotia Duck Tolling Retriever",
            "Old English Sheepdog",
            "Otterhound",
            "Papillon",
            "Parson Russell Terrier",
            "Pekingese",
            "Pembroke Welsh Corgi",
            "Petit Basset Griffon Vendeen",
            "Pharaoh Hound",
            "Plott Hound",
            "Pointer",
            "Polish Lowland Sheepdog",
            "Pomeranian",
            "Poodle (Miniature)",
            "Poodle (Standard)",
            "Poodle (Toy)",
            "Portuguese Podengo",
            "Portuguese Water Dog",
            "Pug",
            "Puli",
            "Pumi",
            "Pyrenean Shepherd",
            "Rat Terrier",
            "Redbone Coonhound",
            "Rhodesian Ridgeback",
            "Rottweiler",
            "Russell Terrier",
            "Saarloos Wolfdog",
            "Saint Bernard",
            "Saluki",
            "Samoyed",
            "Schipperke",
            "Scottish Deerhound",
            "Scottish Terrier",
            "Sealyham Terrier",
            "Shetland Sheepdog",
            "Shiba Inu",
            "Shih Tzu",
            "Siberian Husky",
            "Silky Terrier",
            "Skye Terrier",
            "Sloughi",
            "Small Munsterlander Pointer",
            "Smooth Fox Terrier",
            "Soft Coated Wheaten Terrier",
            "Spanish Water Dog",
            "Spinone Italiano",
            "Stabyhoun",
            "Standard Schnauzer",
            "Sussex Spaniel",
            "Swedish Lapphund",
            "Swedish Vallhund",
            "Thai Ridgeback",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Toy Fox Terrier",
            "Treeing Tennessee Brindle",
            "Treeing Walker Coonhound",
            "Vizsla",
            "Weimaraner",
            "Welsh Springer Spaniel",
            "Welsh Terrier",
            "West Highland White Terrier",
            "Whippet",
            "Wire Fox Terrier",
            "Wirehaired Pointing Griffon",
            "Wirehaired Vizsla",
            "Xoloitzcuintli",
            "Yorkshire Terrier"
        ];
    }
}
